import { Route, Vehicle, Service, Review, FAQ } from '@/types';

export const routes: Route[] = [
    {
        id: '1',
        name: 'Makkah to Madinah',
        from: 'Makkah',
        to: 'Madinah',
        distance: '450 km',
        duration: '4-5 hours',
        price: 600,
        description: 'Comfortable journey between the two holy cities',
        slug: 'makkah-to-madinah',
    },
    {
        id: '2',
        name: 'Madinah to Makkah',
        from: 'Madinah',
        to: 'Makkah',
        distance: '450 km',
        duration: '4-5 hours',
        price: 600,
        description: 'Safe and reliable transport to Makkah',
        slug: 'madinah-to-makkah',
    },
    {
        id: '3',
        name: 'Jeddah Airport to Makkah',
        from: 'Jeddah Airport (JED)',
        to: 'Makkah',
        distance: '85 km',
        duration: '1-1.5 hours',
        price: 200,
        description: 'Direct airport transfer to Makkah hotels',
        slug: 'jeddah-airport-to-makkah',
    },
    {
        id: '4',
        name: 'Jeddah Airport to Madinah',
        from: 'Jeddah Airport (JED)',
        to: 'Madinah',
        distance: '420 km',
        duration: '4-4.5 hours',
        price: 550,
        description: 'Convenient airport pickup to Madinah',
        slug: 'jeddah-airport-to-madinah',
    },
    {
        id: '5',
        name: 'Makkah Ziyarat',
        from: 'Makkah Hotels',
        to: 'Ziyarat Sites',
        distance: 'Varies',
        duration: '4-6 hours',
        price: 300,
        description: 'Visit important Islamic historical sites in Makkah',
        slug: 'makkah-ziyarat',
    },
    {
        id: '6',
        name: 'Madinah Ziyarat',
        from: 'Madinah Hotels',
        to: 'Ziyarat Sites',
        distance: 'Varies',
        duration: '4-6 hours',
        price: 300,
        description: 'Explore sacred sites in Madinah with expert guide',
        slug: 'madinah-ziyarat',
    },
];

export const vehicles: Vehicle[] = [
    {
        id: '1',
        name: 'GMC Yukon Denali',
        type: 'VIP SUV',
        passengers: 7,
        luggage: 6,
        image: '/vehicles/gmc_yukon.png',
        features: ['Leather Interior', 'Wi-Fi Onboard', 'Climate Control', 'Premium Sound'],
        priceMultiplier: 1.8,
        description: 'Elite comfort for families and VIPs',
    },
    {
        id: '2',
        name: 'Toyota Hiace VIP',
        type: 'Luxury Van',
        passengers: 10,
        luggage: 10,
        image: '/vehicles/toyota_hiace.png',
        features: ['Reclining Seats', 'Extra Legroom', 'USB Charging', 'Large Windows'],
        priceMultiplier: 1.6,
        description: 'Premium group travel experience',
    },
    {
        id: '3',
        name: 'Toyota Coaster VIP',
        type: 'VIP Bus',
        passengers: 22,
        luggage: 25,
        image: '/vehicles/toyota_coaster.png',
        features: ['Professional Driver', 'PA System', 'Individual AC', 'Comfort Seating'],
        priceMultiplier: 2.8,
        description: 'Luxury for large groups and tours',
    },
    {
        id: '4',
        name: 'GMC Tahoe Premier',
        type: 'Premium SUV',
        passengers: 6,
        luggage: 5,
        image: '/vehicles/gmc_tahoe.png',
        features: ['Panoramic Roof', 'Heated Seats', 'GPS Navigation', 'Smooth Drive'],
        priceMultiplier: 1.7,
        description: 'Modern luxury for a smooth journey',
    },
    {
        id: '5',
        name: 'Toyota Granvia',
        type: 'Executive MPV',
        passengers: 6,
        luggage: 7,
        image: '/vehicles/toyota_granvia.png',
        features: ['Captain Chairs', 'Ambient Lighting', 'Quiet Cabin', 'Electric Doors'],
        priceMultiplier: 2.0,
        description: 'The ultimate in executive transfers',
    },
    {
        id: '6',
        name: 'Hyundai H1 Starex',
        type: 'Family Van',
        passengers: 8,
        luggage: 8,
        image: '/vehicles/hyundai_starex.png',
        features: ['Dual AC', 'Flexible Seating', 'Reliable', 'Spacious'],
        priceMultiplier: 1.3,
        description: 'Dependable choice for medium families',
    },
    {
        id: '7',
        name: 'Toyota Hiace GL',
        type: 'Standard Van',
        passengers: 12,
        luggage: 12,
        image: '/vehicles/toyota_hiace.png',
        features: ['Air Conditioning', 'Ample Luggage space', 'Robust', 'Clean'],
        priceMultiplier: 1.4,
        description: 'The workhorse of pilgrim transport',
    },
    {
        id: '8',
        name: 'GMC Yukon SLT',
        type: 'Standard SUV',
        passengers: 7,
        luggage: 6,
        image: '/vehicles/gmc_yukon.png',
        features: ['Comfortable Ride', 'Strong AC', 'Child Locks', 'Large Trunk'],
        priceMultiplier: 1.5,
        description: 'Standard luxury for your sacred journey',
    },
    {
        id: '9',
        name: 'Toyota Coaster Standard',
        type: 'Group Bus',
        passengers: 26,
        luggage: 20,
        image: '/vehicles/toyota_coaster.png',
        features: ['Reliable Engine', 'Safety Belts', 'Cool Air', 'Experienced Driver'],
        priceMultiplier: 2.5,
        description: 'Reliable group transport across cities',
    },
    {
        id: '10',
        name: 'GMC Tahoe Z71',
        type: 'Off-road Luxury',
        passengers: 7,
        luggage: 5,
        image: '/vehicles/gmc_tahoe.png',
        features: ['Rugged Build', 'High Clearance', 'Bose System', 'Bluetooth'],
        priceMultiplier: 1.75,
        description: 'Powerful SUV for all road conditions',
    },
    {
        id: '11',
        name: 'Toyota Hiace Commuter',
        type: 'Economy Van',
        passengers: 14,
        luggage: 8,
        image: '/vehicles/toyota_hiace.png',
        features: ['Maximum Capacity', 'Efficient', 'Reliable AC', 'Stable'],
        priceMultiplier: 1.2,
        description: 'Best value for larger groups',
    },
    {
        id: '12',
        name: 'Toyota Granvia Luxury',
        type: 'VIP MPV',
        passengers: 6,
        luggage: 7,
        image: '/vehicles/toyota_granvia.png',
        features: ['Ottoman Seats', 'Premium Leather', 'Sunshade', 'Quiet Interior'],
        priceMultiplier: 2.2,
        description: 'High-end comfort for discerning pilgrims',
    },
    {
        id: '13',
        name: 'Hyundai H1 Premium',
        type: 'Luxury MPV',
        passengers: 7,
        luggage: 8,
        image: '/vehicles/hyundai_starex.png',
        features: ['Upgraded Interior', 'Smooth Suspension', 'Rear Camera', 'Privacy Glass'],
        priceMultiplier: 1.5,
        description: 'Enhanced comfort for family tours',
    },
    {
        id: '14',
        name: 'GMC Yukon XL',
        type: 'Extra-Large SUV',
        passengers: 8,
        luggage: 10,
        image: '/vehicles/gmc_yukon.png',
        features: ['Extended Length', 'Huge Cargo Area', 'Rear Ent.', 'V8 Power'],
        priceMultiplier: 1.9,
        description: 'Maximum space for large families and luggage',
    },
    {
        id: '15',
        name: 'Toyota Coaster Deluxe',
        type: 'Premium Bus',
        passengers: 22,
        luggage: 30,
        image: '/vehicles/toyota_coaster.png',
        features: ['Overhead Racks', 'Reading Lights', 'Large Trunk', 'Premium AC'],
        priceMultiplier: 3.0,
        description: 'Premium choice for long distance group travel',
    },
];

export const services: Service[] = [
    {
        id: '1',
        name: 'Umrah Taxi Service',
        description: 'Dedicated taxi service for Umrah pilgrims with experienced drivers',
        icon: 'Kaaba',
        features: [
            'Licensed and experienced drivers',
            'Clean and well-maintained vehicles',
            'Fixed pricing with no hidden charges',
            'Door-to-door service',
        ],
        slug: 'umrah-taxi',
    },
    {
        id: '2',
        name: 'Airport Transfer',
        description: 'Reliable airport pickup and drop-off services',
        icon: 'Plane',
        features: [
            'Flight tracking',
            'Meet and greet service',
            'Luggage assistance',
            '24/7 availability',
        ],
        slug: 'airport-transfer',
    },
    {
        id: '3',
        name: 'Ziyarat Tours',
        description: 'Guided tours to important Islamic historical sites',
        icon: 'MapPin',
        features: [
            'Knowledgeable guides',
            'Flexible itineraries',
            'All major sites covered',
            'Group discounts available',
        ],
        slug: 'ziyarat-tours',
    },
    {
        id: '4',
        name: 'City-to-City Transfers',
        description: 'Comfortable intercity travel between Makkah, Madinah, and Jeddah',
        icon: 'Navigation',
        features: [
            'Direct routes',
            'Rest stops included',
            'Multiple vehicle options',
            'Competitive pricing',
        ],
        slug: 'city-transfers',
    },
    {
        id: '5',
        name: 'Family & Group Transport',
        description: 'Spacious vehicles for families and groups of all sizes',
        icon: 'Users',
        features: [
            'Vehicles for 3-26 passengers',
            'Child seats available',
            'Extra luggage space',
            'Group discount rates',
        ],
        slug: 'group-transport',
    },
];

export const reviews: Review[] = [
    {
        id: '1',
        name: 'Ahmed Al-Rashid',
        rating: 5,
        comment: 'Excellent service! The driver was very professional and the car was clean. Made our Umrah journey very comfortable.',
        date: '2024-01-15',
        location: 'Saudi Arabia',
    },
    {
        id: '2',
        name: 'Fatima Hassan',
        rating: 5,
        comment: 'Very reliable and punctual. The booking process was easy and the WhatsApp communication was very helpful.',
        date: '2024-01-10',
        location: 'UAE',
    },
    {
        id: '3',
        name: 'Muhammad Ibrahim',
        rating: 5,
        comment: 'Best taxi service for Umrah! Fixed prices, no haggling, and very comfortable vehicles. Highly recommended!',
        date: '2024-01-05',
        location: 'Pakistan',
    },
    {
        id: '4',
        name: 'Aisha Khan',
        rating: 5,
        comment: 'The Ziyarat tour was amazing. Our guide was knowledgeable and the driver was very patient. Great experience!',
        date: '2023-12-28',
        location: 'India',
    },
];

export const faqs: FAQ[] = [
    {
        id: '1',
        question: 'How do I book a taxi?',
        answer: 'You can book through our website by filling the booking form, or directly via WhatsApp by clicking the "Book on WhatsApp" button. You can also call us 24/7.',
    },
    {
        id: '2',
        question: 'Are the prices fixed?',
        answer: 'Yes, all our prices are fixed with no hidden charges. The price you see is the price you pay.',
    },
    {
        id: '3',
        question: 'Do you provide airport pickup?',
        answer: 'Yes, we provide 24/7 airport pickup and drop-off services from Jeddah Airport to Makkah and Madinah.',
    },
    {
        id: '4',
        question: 'What vehicles do you have?',
        answer: 'We have sedans (3 passengers), Hiace (11 passengers), and Coaster buses (26 passengers) to accommodate groups of all sizes.',
    },
    {
        id: '5',
        question: 'Are your drivers licensed?',
        answer: 'Yes, all our drivers are fully licensed, experienced, and trained to provide the best service to Umrah pilgrims.',
    },
    {
        id: '6',
        question: 'Can I cancel or reschedule my booking?',
        answer: 'Yes, you can cancel or reschedule. Please check our refund policy page for detailed terms and conditions.',
    },
    {
        id: '7',
        question: 'Do you provide Ziyarat tours?',
        answer: 'Yes, we offer guided Ziyarat tours in both Makkah and Madinah covering all important Islamic historical sites.',
    },
    {
        id: '8',
        question: 'Is there a minimum booking time?',
        answer: 'We recommend booking at least 24 hours in advance, but we also accept last-minute bookings subject to availability.',
    },
];

export const cities = [
    'Makkah',
    'Madinah',
    'Jeddah',
    'Jeddah Airport (JED)',
    'Taif',
    'Yanbu',
];

export const whyChooseUs = [
    {
        id: '1',
        title: 'Licensed Drivers',
        description: 'All our drivers are fully licensed and experienced',
        icon: 'ShieldCheck',
    },
    {
        id: '2',
        title: 'Fixed Pricing',
        description: 'Transparent pricing with no hidden charges',
        icon: 'DollarSign',
    },
    {
        id: '3',
        title: '24/7 Support',
        description: 'Round-the-clock customer support',
        icon: 'Clock',
    },
    {
        id: '4',
        title: 'Clean Vehicles',
        description: 'Well-maintained and sanitized vehicles',
        icon: 'Sparkles',
    },
];
